server:
   port: 8001
spring:
  application:
    name: user-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservice
    password: root
eureka:
  instance:
    hostname: localhost